### ISSUE TITLE
Incompatible with Signal?

### ISSUE THREAD

**Issue by tuxayo** [LibreSignal/LibreSignal#25] opened 2016-03-31 08:54 UTC
I already have Signal installed, when I try to install LibreSignal, I get a generic install failure.
The log cat shows:

```
W/ActivityManager(23744): No content provider found for permission revoke: file:///data/data/org.fdroid.fdroid/cache/temp/org.libresignal_193.apk
W/ActivityManager(23744): No content provider found for permission revoke: file:///data/data/org.fdroid.fdroid/cache/temp/org.libresignal_193.apk
W/PackageManager(23744): Can't install because provider name org.thoughtcrime.provider.securesms (in package org.libresignal) is already used by org.thoughtcrime.securesms
W/PackageManager(23744): Package couldn't be installed in /data/app/org.libresignal-1.apk
E/AppDetails(14595): Installer aborted with errorCode: 3
```

Can someone confirm that the incompatibly is normal? (And not a renaming that was forgotten)
If it's the case, should we update the readme and the app description in F-Droid to warn users about this?

**Comment by mimi89999** [comment] 2016-03-31 10:11
Yes, you need to uninstall Signal to install LibreSignal. You cannot have both running at the same time.

**Comment by mimi89999** [comment] 2016-03-31 10:16
I don't think that warning users about this is needed. How many users will want to install two vetsions in parallel? When installation will fail, they will understand that you cannot use two versions at the same time...

**Comment by mimi89999** [comment] 2016-03-31 10:17
Closing this issue because it's not a bug, but an expected behaviour.

**Closed as completed** 2016-03-31 10:16 UTC

**Comment by tuxayo** [comment] 2016-04-01 10:25
> How many users will want to install two vetsions in parallel? When installation will fail, they will understand that you cannot use two versions at the same time...

I should have understood but I did only when seeing the logcat, I hope I'll be the only one.

Thanks
