### ISSUE TITLE
Says my version is going to expire

### ISSUE THREAD

**Issue by xenithorb** [LibreSignal/LibreSignal#42] opened 2016-06-14 18:41 UTC
Is this dead and gone or what. Using the eutopia.cz repo with F-Droid

I read the giant shitstorm that is #37 and I don't really know which way is up at this point

**Comment by noctilon** [comment] 2016-06-14 19:07
It's time to abandon ship. Switch over to [Conversations](https://conversations.im) / [ChatSecure](https://chatsecure.org/) / [Zom](https://zom.im/) (if you can) or wait for E2EE support in [Vector](https://vector.im/).

**Comment by pejakm** [comment] 2016-06-14 20:00
Or switch to [Kontalk](https://kontalk.org/). Or download Signal from [ApkMirror](http://www.apkmirror.com/apk/open-whisper-systems/signal-private-messenger/) and use it along with [microG](https://microg.org/).

**Comment by herbsmn** [comment] 2016-06-14 20:39
Hey @mimi89999. Is it not worth it to update your repo one more time? 9 days is a small window of time to pack up shop and move to another communications platform. I know libresignal isn't a long term solution, since the centralized server provider is hostile, but now that we know that the end is definitely near, it'd be great to be able to buy libresignal users a little bit more time. Also, with the OWS license change, it looks like ChatSecure with OMEMO is coming sooner than later to iOS. Would be nice to be able to use LibreSignal up until the time they can recommend to family and friends that use ChatSecure with OMEMO on iOS.

**Comment by mimi89999** [comment] 2016-06-14 20:53
@herbsmn How did you install LibreSignal? If you installed it from the F-Droid archive repo, you wan't receive updates anyway because the app was removed from there...

**Comment by herbsmn** [comment] 2016-06-14 20:57
yeah, i used @xmikos's experimental F-Droid repo. I didn't know he removed it. what repo has the most up to date version? I can compile from source. https://github.com/JavaJens/TextSecure seems to not have been updated since Feb 21st.

**Comment by mimi89999** [comment] 2016-06-14 20:59
I wasn't writing about xmikos repo, but about the F-Droid archive repo....

**Comment by mimi89999** [comment] 2016-06-14 21:01
@xmikos What do you think about making the last LibreSignal update?

**Comment by noctilon** [comment] 2016-06-14 21:12
@pejakm

> Or switch to Kontalk.

Regarding Kontalk, please keep in mind that this project currently uses [E2EE (without PFS) based on PGP](https://github.com/kontalk/specs/blob/master/encryption.md). There are plans to chance this, though (see https://github.com/kontalk/androidclient/issues/132). Furthermore, there is no [iOS client](https://github.com/kontalk/iosclient) available yet.

The [crypto messenger comparison chart](http://www.titus-stahl.de/blog/2016/05/15/comparing-encrypted-messengers/) created by Titus Stahl may be good point to start for everyone who is in need of a quick client/feature overview. 

**Update**: I found [another more detailed comparison chart](https://docs.google.com/spreadsheets/d/1tv5QTuoS29YwApP7i2OKe9aLrZZIwgY-f5b-d73vlI0/) made by the reddit user tiger_respecter.

**Comment by herbsmn** [comment] 2016-06-14 21:19
gotcha. well yeah, with the @xmikos experimental repo, it says LibreSignal has 9 days left to live. One last LibreSignal update would be beautiful and very helpful to many people. It'd give ChatSecure a little bit more time to get OMEMO rocking on iOS now that OWS changed their licensing so that their GPLv3 SignalProtocal can be used in the iOS app store. https://github.com/ChatSecure/ChatSecure-iOS/issues/376#issuecomment-225707513

**Comment by xenithorb** [comment] 2016-06-14 21:26
Clearly a vibrant community here. Sad to see it go to waste. 

Found a new build from another popular repo, but I won't mention it since it will clearly inundate the poor guy. I'm set for now at least.

**Comment by herbsmn** [comment] 2016-06-15 00:24
@xenithorb can you send it to me privately?

**Comment by mimi89999** [comment] 2016-06-15 05:36
What other repo?

**Comment by xenithorb** [comment] 2016-06-15 08:02
I just said I wasn't going to out the repo because it wouldn't be fair to his servers.

**Comment by mimi89999** [comment] 2016-06-15 08:05
Not even PM it to me?

**Comment by xmikos** [comment] 2016-06-15 14:31
I will still provide independent builds in Eutopia.cz F-Droid repository, see here: https://github.com/LibreSignal/LibreSignal/issues/37#issuecomment-226198069

**Comment by mimi89999** [comment] 2016-06-15 14:47
I updated LibreSignal, but I didn't test it because none of my contacts is using Signal/LibreSignal.

**Comment by xmikos** [comment] 2016-06-15 14:55
@mimi89999 Thanks, I will review code diff and test it. If it will be good, I will update F-Droid repo soon (I hope in circa 5 - 8 hours, tomorrow at worst).

**Comment by mimi89999** [comment] 2016-06-15 15:00
It doesn't build. I will do further debugging...

**Comment by mimi89999** [comment] 2016-06-15 15:14
@xmikos Fixed. It builds now.

**Comment by ClubWDW** [comment] 2016-06-17 00:10
Is there a time frame to when this will be updated in F-Droid?

**Comment by idumych** [comment] 2016-06-17 16:49
I posted on the Fdroid repo github page as well, but what does this mean for LibreSignal users long term? Supposedly the project is cancelled, but I just installed LibreSignal 3.16 from Fdroid. I'm guessing these are @xmikos 's builds. Does this mean that the code is just going to be stagnant now and we'll eventually lose parity with Signal official?

**Comment by xmikos** [comment] 2016-06-17 18:18
I couldn't make F-Droid's Vagrant-based buildserver to work again yesterday (like I originally intended). This is why it takes so much time to update :-( I have pretty much given up on it now and will release standard (non-reproducible) build soon (well, it will be build on latest Arch Linux, so it could be reproduced, just not that simply).

**Comment by ClubWDW** [comment] 2016-06-17 20:08
@xmikos Thank you!

**Comment by herbsmn** [comment] 2016-06-17 20:38
Thanks @xmikos!

**Comment by fHbT28B** [comment] 2016-06-17 22:01
Hello guys.
I am not a programmer and not very computer/smartphone oriented. And my English is not the best :-). I just used LibreSignal, because it is an alternative to Signal, which requires Google PlayStore, that I wanted to avoid.
My F-Droid says that my version needs an update, which is not listed. Now I read something like that the project is cancelled. Is that correct? I read something of source codes and anything like that :-). No idea.
I think, LibreSignal quite is nice, because it is compatible to Signal. Is there any possibility to use it furthermore? And in case of not, what can I do alternatively?

**Comment by xmikos** [comment] 2016-06-18 01:42
@fHbT28B I have already uploaded new version to _experimental_ repo on https://fdroid.eutopia.cz, so you can update and still use it. It is only temporary solution, this WebSocket-fork of Signal is really pretty much dead. 

But I will still keep providing independent builds from official Signal sources in _main_ repo and there is some new hope that WebSocket support will be added to official Signal in the future.

**Comment by ClubWDW** [comment] 2016-06-18 01:59
@xmikos Thank you sooo much for your work on this project. It has been great while it lasted. As per your advice (and others) I am going to migrate to another solution. Silence looks promising but I'm having an issue. As it is from the same source, I was hoping you could shed some light on a problem I'm having. Would you look at [this](https://github.com/SilenceIM/Silence/issues/420) and give me your thoughts?

**Comment by fHbT28B** [comment] 2016-06-19 00:10
What is the other solution, which is compatible to other Signal-Users? I have persuadet a lot of friends to use Signal instead of Whatsapp, so that I am compatible with LibreSignal. What is my possibility to be still in contact with them and not to admit, that this solution was not so clever. It was a really hard work to argue :-).
It was discussed about servers, which will not be provided anymore for other users than Signal-Users. Does that mean, it is not compatible anymore? I am really just user. I have no feeling for those computer terms. Is Signal in future (possibly) just compatible to Google Cloud Messanging? It sounded a bit like that.

**Comment by idumych** [comment] 2016-06-19 00:26
@fHbT28B , I suggest to you and anyone else who comes across this thread in the future, check out Conversations. It's in Fdroid and the Play Store. After reading up on this for a couple days, I have found that OMEMO is the same method of end to end encryption that Signal uses. Conversations, and a growing number of other Jabber/XMPP clients support this. You can have identical functionality, using just about any Jabber server you like, to Signal. Additionally, Conversations supports the older OTR encryption method, which means you can still speak securely to users of legacy Jabber apps that haven't added OMEMO yet. 

XMPP+OMEMO is the future. It's what Signal should have been in the first place, based on open standards and interoperable. Talk your Android using friends and family into switching to Conversations. Eventually, Chatsecure (which is crossplatform) will have OMEMO support as well, and you can suggest that to your Apple using contacts. Once OMEMO is more widely adopted, monolithic systems like Signal and Whatsapp will be obsolete. 

https://conversations.im/

https://chatsecure.org/blog/chatsecure-conversations-zom/

https://en.wikipedia.org/wiki/OMEMO

https://github.com/kalkin/gajim-omemo

**Comment by razzor1984** [comment] 2016-06-20 10:14
@idumych

you must differ, technical aspect and User aspects. The most users know that whats app uses now an "Encryption" regardless that its an closed source and nobody knows
how the encryption is implemented(Contact book upload next bad part). The mainstream only sees the word "encryption" an that's the selling point.
The second part are the contacts, you simply cant force your "friends" to transit to an new messenger. So that in mind you will loose a good part of your friends. Your 
contact method from now on, is the old school sms. The bad part on this is, sms is the worst communication method.Its not encrypted and delivers a huge amount of meta data.

Wee can sum it up, contacts are the STOCK VALUE of every messenger, why paid FB so much for whats app ? 

The mainstream doesn't think like an IT- engineer, they don't scrutinize how well code and encryption is implemented.
They only want to use it and if they see the word encryption, they are hooked, and believe every bit of information what the app description offers !!!!
best regards 
Razzor

**Comment by sim6** [comment] 2016-06-20 22:38
Is possible to get the last update via f-droid archive repository? Thanks.

**Comment by dejIO** [comment] 2016-06-21 18:18
For some reason the update doesn't show up in F-Droid. I could directly install the APK from the experimental repo, though, and without any problems.

**Comment by herbsmn** [comment] 2016-06-21 18:46
@sim6 and @dejIO: you gotta get it by adding the experimental repo listed at this website to F-Droid: https://fdroid.eutopia.cz/

**Comment by fHbT28B** [comment] 2016-06-21 18:50
And how do I activate this? I get the error that this source is not signed.

**Comment by herbsmn** [comment] 2016-06-21 18:54
@fHbT28B try updating the repo a few times. hopefully it will grab the signature.

**Comment by fHbT28B** [comment] 2016-06-21 19:05
I restarted my smartphone and it still doesn't work.
I downloaded the apk "org.thoughtcrime.securesms_10194.apk" from:
https://eutopia.cz/experimental/fdroid/repo/?fingerprint=A0E4D1D912D8B81809AB18F5B7CF562CD1A10533ED4F7B25E595ABC8D862AD87

But this apk is also not installable. This seems very strange.

**Comment by herbsmn** [comment] 2016-06-21 19:07
Did you add the https://eutopia.cz/experimental/fdroid/repo repo to your f-droid app? You should do that rather than downloading the apk.

**Comment by fHbT28B** [comment] 2016-06-21 19:18
Of course. The first time without fingerprint (message: "unsigned"), the second time with fingerprint (message: "unverified"). Description: "This repository has not been used yet. You need to enable it to view the apps it provides."
I do not understand. What does that mean?

**Comment by herbsmn** [comment] 2016-06-21 19:22
to the right of the repo in the repo list is it green or grey? should be green to activate it.

**Comment by mimi89999** [comment] 2016-06-21 19:26
If you installed LibreSignal from the F-Droid archive repo before, you can't just update to the version in the Eutopia repo. You will need to uninstall the former and then install the app from Eutopia.

**Comment by fHbT28B** [comment] 2016-06-21 19:37
@herbsmn: The repository is activated. It is green and on the right. But under the repository title (on the left) is written in grey: "Unveryfied".

@mimi89999: If it is not possible to use the repository of FDroid (it is making problems in the moment), can I install the downloaded apk from the directlink https://eutopia.cz/experimental/fdroid/repo after deinstalling the old version? What is with public and private key? I simply get new ones?

**Comment by herbsmn** [comment] 2016-06-21 22:13
@xmikos runs the repo. maybe he can help you @fHbT28B

**Comment by tuxayo** [comment] 2016-06-22 09:07
@fHbT28B @mimi89999 don't forget to export your messages before uninstalling and also the whole process will reset your encrypted sessions.

**Comment by fHbT28B** [comment] 2016-06-23 07:39
It  is right, that the former version has to be deleted before installing the new one. This is a point that has to be registered clearly somewhere here, because there are certainly many users installing it from F-Droid.
The problem with F-Droid is not solved yet. I just intstalled the offered apk.

**Comment by 1dud3** [comment] 2016-11-01 08:39
My version is going to be expired in a couple of days. Any chance for an update? Thank you so far.

**Comment by tuxayo** [comment] 2016-11-01 08:51
We shouldn't even have had the last update, I think it's really the end now.
Alternatives that I know are
- switch to Conversations https://conversations.im/
- switch to Signal from this independent repo https://fdroid.eutopia.cz/
  - use MicroG if you don't have/want Google Play services installed (I recall ready that the GCM part works well)
  - see the [FAQ](https://github.com/LibreSignal/LibreSignal/wiki/FAQ#how-to-migrate-to-libresignal-and-keep-all-conversations-groups-and-so-on) for migrating without losing data and encrypted sessions.
- switch to Signal from the Play Store
  - see the [FAQ](https://github.com/LibreSignal/LibreSignal/wiki/FAQ#how-to-migrate-to-libresignal-and-keep-all-conversations-groups-and-so-on) for migrating without losing data and encrypted sessions.

**Comment by 1dud3** [comment] 2016-11-01 19:51
I am familiar with these options, but cannot switch to Conversations/XMPP yet without OMEO support for iOS.

Btw does MicroG use Google infrastructure/server to reproduce GCM?

**Comment by herbsmn** [comment] 2016-11-01 20:05
OMEMO support for iOS isn't even in Beta yet. Looks like Beta might drop next week. https://github.com/ChatSecure/ChatSecure-iOS/issues/376#issuecomment-257625846 This obviously is taking longer than people thought that it would, but my vote is to update LibreSignal one more time so that we can all have a smooth transition to Conversations and Chatsecure. This would prevent people from having to use a non-SignalProtocol messenging app inbetween the time LibreSignal dies and OMEMO on iOS is born.

**Comment by herbsmn** [comment] 2016-11-01 20:06
what do you say @mimi89999? One more time?

**Comment by xmikos** [comment] 2016-11-01 20:11
@1dud3 Yes, microG uses Google infrastructure, it is just independent third-party client to it. But I don't see this like a big problem, Signal servers are IMHO much more likely to be attacked by nation state than Google servers (there is not much metadata in GCM push messages).

Problem is with Google Play Services (which is big  fat backdoor to your phone) and microG fixes this.

**Comment by xmikos** [comment] 2016-11-01 20:16
@1dud3 If you are OK with centralized service like Signal, you can use [Wire](https://wire.com) instead. It also uses Signal protocol (their own implementation of Axolotl double ratchet) and is open source, but they are much more friendly towards FOSS community than Moxie. And it doesn't need GCM.

**Comment by mimi89999** [comment] 2016-11-02 14:01
When will the current version of LS expire?

**Comment by 1dud3** [comment] 2016-11-02 14:25
In three days.

**Comment by mimi89999** [comment] 2016-11-02 14:38
Maybe I will update LS Friday so Saturday if I will have time...

**Comment by paride** [comment] 2016-11-02 14:49
Hey @mimi89999, will you consider trying to send the patch upstream?

**Comment by mimi89999** [comment] 2016-11-02 14:58
I will just update LS. I won't implement websocket in Signal. At least not in the next days or weeks...

**Comment by mimi89999** [comment] 2016-11-02 14:59
And if I update LS, it will really be the last update.

**Comment by nidico** [comment] 2016-11-02 17:17
> Maybe I will update LS Friday so Saturday if I will have time...

This would be very appreciated, thanks!

**Comment by mimi89999** [comment] 2016-11-02 18:40
I pulled from upstream, but I still need to check several things... Please, don't use it yet...

**Comment by mimi89999** [comment] 2016-11-02 18:45
@xmikos Hmm... They added giphy. What do you think about that?

**Comment by mimi89999** [comment] 2016-11-02 19:56
I am testing it right now...

**Comment by no1984** [comment] 2016-11-02 21:22
I'm using LibreSignal, and until today I didn't know that LibreSignal is abandoned. My version will expire in four days.
It would be great if there would be one last update! That would give me some more time to look for a new messaging solution, save my data, inform my contacts and so on.
Thank you very much for your work!

**Comment by mimi89999** [comment] 2016-11-02 21:46
@no1984 The repo is already updated. I only need to test LS (help would be appreciated). Also waiting for an opinion about Giphy in LS and after that, I can ask @xmikos to update his F-Droid repo.

**Comment by xmikos** [comment] 2016-11-02 22:32
@mimi89999 I have looked at the code and it seems good. They are even providing secure TLS proxy for Giphy lookups.

There is also blogpost by Moxie explaining it: [Signal and GIPHY](https://whispersystems.org/blog/giphy-experiment/)

Of course it can still be potentially abused for correlation of requests, but user don't have to use it, so it is IMHO okay (btw. Wire also integrates with Giphy).

**Comment by mimi89999** [comment] 2016-11-03 07:21
@xmikos OK, so you can update the Eutopia experimental repo.

**Comment by no1984** [comment] 2016-11-03 20:33
@mimi89999 Thanks a lot!

**Comment by mimi89999** [comment] 2016-11-05 15:24
Closing that issue since I updated LS.

**Closed as completed** 2016-11-05 15:24 UTC

**Comment by nidico** [comment] 2016-11-05 15:41
Thanks for the update!
