### ISSUE TITLE
Change packageName

### ISSUE THREAD

**Issue by mimi89999** [LibreSignal/LibreSignal#12] opened 2016-03-15 11:48 UTC
https://gitlab.com/fdroid/fdroiddata/merge_requests/1288#note_4264094

**Comment by dotlambda** [comment] 2016-03-15 17:15
You could do this using gradle so that upstream changes can be merged without worrying about it.

Actually, I'm not sure if gradle provides such a functionality, but that's what I'm used to from gulp and the web development world.

**Comment by mimi89999** [comment] 2016-03-15 18:34
I will do so...
Any propositions for the name?

**Comment by mimi89999** [comment] 2016-03-15 18:57
"org.libresignal"?

**Comment by mimi89999** [comment] 2016-03-15 20:13
@SecUpwN

**Comment by xmikos** [comment] 2016-03-15 20:39
I am not sure this is good choice. If you change package name, nobody will be able to switch from original Signal to LibreSignal without losing data (and even worse, everyone using current build of LibreSignal will lose data too). This is huge problem.

**Comment by mimi89999** [comment] 2016-03-15 20:52
@xmikos That's what I wrote as a comment under that MR....

**Comment by mimi89999** [comment] 2016-03-15 21:05
In the worst case, you could add a line in prebuild that will "sed" package name...

**Comment by mvdan** [comment] 2016-03-15 21:11
@xmikos this is already the case because the signatures will be different.

**Comment by mimi89999** [comment] 2016-03-15 21:18
I was thinking about switching Eutopia <--------> F-Droid.

**Comment by mvdan** [comment] 2016-03-15 21:20
My point is that eutopia should have been using a different package id altogether. After all, they distribute LibreSignal, not Sinal (AFAIK).

**Comment by mimi89999** [comment] 2016-03-15 21:22
Yes, but since they didn't...

**Comment by mvdan** [comment] 2016-03-15 21:23
We won't accept libresignal under the signal package name, that's for sure. How you fix that on your end or with eutopia is up to you guys.

**Comment by mimi89999** [comment] 2016-03-15 21:47
I will change the package name and @xmikos will just "sed" the package name in prebuild...

Any propositions for a new package name?

**Comment by ghost** [comment] 2016-03-15 21:55
Gradle should support `applicationId "com.example.my.app"` to change it on the fly.

**Comment by mimi89999** [comment] 2016-03-15 22:00
Maybe "org.libresignal" as package name? What do you think?

**Comment by xmikos** [comment] 2016-03-15 23:04
I am OK with "sed"ing it just for my eutopia.cz repo in prebuild script. I will definitely not change package name in my builds, this would upset a lot of people.

@mvdan It is not already the case, because if you have rooted phone, you can make backup with [oandbackup](https://f-droid.org/repository/browse/?fdfilter=oandbackup&fdid=dk.jens.backup) while you have Signal installed, switch to LibreSignal and then restore that backup (I have done it like this myself).

**Comment by mvdan** [comment] 2016-03-15 23:05
If you're using root, nothing stops you from porting the data from one package name to another. The thing here is whether the tool, such as oandbackup, supports this.

**Comment by xmikos** [comment] 2016-03-15 23:11
@mvdan No, it doesn't (and neither does TitaniumBackup or other backup tools I know of).

But like I said I am OK with keeping original package name just for my eutopia.cz repo.

**Comment by dotlambda** [comment] 2016-03-16 00:50
@xmikos How about publishing two versions in your repo, one called "LibreSignal (legacy)" and maintaining the current id for this one? This shouldn't upset anybody and makes reproducible builds possible.

**Closed as completed** 2016-03-16 17:53 UTC

**Comment by SecUpwN** [comment] 2016-03-16 21:04
Regarding https://github.com/LibreSignal/LibreSignal/issues/12#issuecomment-197010819: Have a read of my discovery at https://github.com/JavaJens/TextSecure/issues/53#issuecomment-159293479.

**Comment by mimi89999** [comment] 2016-03-16 21:07
What about the folder name in /data/data/?

**Comment by mimi89999** [comment] 2016-03-16 21:09
I left the name of the backup file: "SignalPlaintextBackup.xml", but that won't help users to keep old keys...

**Comment by SecUpwN** [comment] 2016-03-16 21:20
> What about the folder name in /data/data/?

Not sure what you mean. @mimi89999, have you had a look at how @SMSSecure solved that Issue?

**Comment by mimi89999** [comment] 2016-03-16 21:38
If you change the package name, the app will appear as a completly diffrent app. The user will have to export conversation log, register with the "new" app and generate **_new keys**_, and then import conversation log. His contacts will have to accept his new key. I did like that and it was an awful experience geting my contacts to accept the new key/identity...

**Comment by SecUpwN** [comment] 2016-03-19 15:00
> If you change the package name, the app will appear as a completly diffrent app.

Does that mean that https://github.com/LibreSignal/LibreSignal/commit/444c0db79b1bd91736479a9a0b4a33f961563399 now prevents an update from the APK installed from https://eutopia.cz/experimental/fdroid/repo/? I still cannot find our official `LibreSignal` release on F-Droid.

**Comment by mimi89999** [comment] 2016-03-19 15:12
Eutopia "sed" the package name to keep the old one.

**Comment by mimi89999** [comment] 2016-03-19 15:14
https://github.com/xmikos/fdroiddata/pull/14

**Comment by mimi89999** [comment] 2016-03-20 08:41
LibreSignal is in the F-Droid archive repo.

**Comment by mimi89999** [comment] 2016-03-20 08:45
The F-Droid link in this repo doesn't work.

**Comment by SecUpwN** [comment] 2016-03-20 12:33
> The F-Droid link in this repo doesn't work.

@mimi89999, what do you mean? Of course it does not work _yet_ as long as it is not in the official repo.

**Comment by mimi89999** [comment] 2016-03-20 12:42
Check my last commit...

**Comment by mimi89999** [comment] 2016-03-20 13:06
Now if you enable the archive repo in F-Droid and click on the link in the repo, F-Droid will show the app.

**Comment by SecUpwN** [comment] 2016-03-20 13:49
> Now if you enable the archive repo in F-Droid and click on the link in the repo, F-Droid will show the app.

Awesome. Hoping to see `LibreSignal` in the native F-Droid repo soon. :+1:
